# -*- coding: utf-8 -*-
# Generated by Django 1.11.21 on 2019-07-29 23:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='WebpayServicesCancellationModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(blank=True, max_length=100, verbose_name=b'Token')),
                ('buyOrder', models.CharField(max_length=42, unique=True, verbose_name=b'Orden Compra de la tienda')),
                ('authorizationCode', models.CharField(blank=True, max_length=8, verbose_name=b'C\xc3\xb3digo autorizaci\xc3\xb3n de la transacci\xc3\xb3n')),
                ('authorizationDate', models.CharField(blank=True, max_length=100, null=True, verbose_name=b'Fecha y hora de la autorizaci\xc3\xb3n')),
                ('balance', models.CharField(blank=True, max_length=20, null=True, verbose_name=b'Balance')),
                ('nullifiedAmount', models.CharField(blank=True, max_length=15, null=True, verbose_name=b'Monto anulado')),
                ('payment_type', models.CharField(blank=True, choices=[(b'NORMAL', b'Webpay Normal'), (b'ONECLICK', b'Webpay OneClick')], max_length=15, null=True, verbose_name=b'Tipo de pago anulado')),
                ('commerceCode', models.CharField(blank=True, max_length=80, verbose_name=b'C\xc3\xb3digo del comercio')),
                ('date_cancellation', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'webpay_services_cancellation',
                'verbose_name': 'Cancelacion de ordenes de compra Webpay',
            },
        ),
    ]
