# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-06-07 17:13
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='WebpayOneClickInscription',
            fields=[
                ('user', models.CharField(max_length=100, primary_key=True, serialize=False, verbose_name=b'Username del usuario del comercio')),
                ('token', models.CharField(blank=True, max_length=300, verbose_name=b'Token proporcionado por Transbank')),
                ('tbk_user', models.CharField(blank=True, max_length=200, verbose_name=b'Username del usuario en Transbank')),
                ('response_code', models.CharField(blank=True, max_length=10, verbose_name=b'C\xc3\xb3digo respuesta de la autorizacion')),
                ('authorization_code', models.CharField(blank=True, max_length=8, verbose_name=b'C\xc3\xb3digo autorizaci\xc3\xb3n de la transacci\xc3\xb3n')),
                ('creditcard_type', models.CharField(blank=True, max_length=10, verbose_name=b'Tipo de tarjeta inscrita por el cliente')),
                ('card_number', models.CharField(blank=True, max_length=4, verbose_name=b'\xc3\x9altimos 4 n\xc3\xbameros de la tarjeta')),
                ('inscrito', models.BooleanField(default=False, verbose_name=b'Esta inscrito correctamente')),
                ('date_inscription', models.DateTimeField(auto_now=True)),
                ('custom', models.CharField(blank=True, max_length=250)),
            ],
            options={
                'db_table': 'webpay_oneclick_inscription',
                'verbose_name': 'Webpay OneClick Inscription',
            },
        ),
        migrations.CreateModel(
            name='WebpayOneClickPayment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('buy_order', models.CharField(max_length=42, unique=True, verbose_name=b'Orden Compra de la tienda')),
                ('amount', models.PositiveIntegerField(default=0, verbose_name=b'Monto transacci\xc3\xb3n')),
                ('authorization_code', models.CharField(blank=True, max_length=8, verbose_name=b'C\xc3\xb3digo autorizaci\xc3\xb3n de la transacci\xc3\xb3n')),
                ('credit_card_type', models.CharField(blank=True, max_length=10, verbose_name=b'Tipo de tarjeta inscrita por el cliente')),
                ('last4_card_digits', models.CharField(blank=True, max_length=4, verbose_name=b'\xc3\x9altimos 4 n\xc3\xbameros de la tarjeta')),
                ('transaction_id', models.CharField(blank=True, max_length=4, verbose_name=b'Transaction ID')),
                ('response_code', models.CharField(blank=True, max_length=10, verbose_name=b'C\xc3\xb3digo respuesta de la autorizacion')),
                ('payment_date', models.DateTimeField(auto_now=True)),
                ('custom', models.CharField(blank=True, max_length=250)),
                ('inscription', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='oneclick.WebpayOneClickInscription')),
            ],
            options={
                'db_table': 'webpay_oneclick_payment',
                'verbose_name': 'Webpay OneClick Payment',
            },
        ),
    ]
