# Generated by Django 3.1 on 2021-02-08 15:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('oneclick', '0002_auto_20190727_1603'),
    ]

    operations = [
        migrations.CreateModel(
            name='WebpayOneClickMultipleInscription',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=100, verbose_name='Username del usuario del comercio')),
                ('token', models.CharField(blank=True, max_length=300, verbose_name='Token proporcionado por Transbank')),
                ('tbk_user', models.CharField(blank=True, max_length=200, verbose_name='Username del usuario en Transbank')),
                ('response_code', models.CharField(blank=True, max_length=10, verbose_name='Código respuesta de la autorizacion')),
                ('authorization_code', models.CharField(blank=True, max_length=8, verbose_name='Código autorización de la transacción')),
                ('creditcard_type', models.CharField(blank=True, max_length=10, verbose_name='Tipo de tarjeta inscrita por el cliente')),
                ('card_number', models.CharField(blank=True, max_length=4, verbose_name='Últimos 4 números de la tarjeta')),
                ('inscrito', models.BooleanField(default=False, verbose_name='Esta inscrito correctamente')),
                ('date_inscription', models.DateTimeField(auto_now_add=True)),
                ('date_uninscription', models.DateTimeField(default=None, null=True)),
                ('custom', models.CharField(blank=True, max_length=250)),
            ],
            options={
                'verbose_name': 'Webpay OneClick Inscription',
                'db_table': 'webpay_oneclick_multiple_inscription',
            },
        ),
        migrations.AlterField(
            model_name='webpayoneclickinscription',
            name='authorization_code',
            field=models.CharField(blank=True, max_length=8, verbose_name='Código autorización de la transacción'),
        ),
        migrations.AlterField(
            model_name='webpayoneclickinscription',
            name='card_number',
            field=models.CharField(blank=True, max_length=4, verbose_name='Últimos 4 números de la tarjeta'),
        ),
        migrations.AlterField(
            model_name='webpayoneclickinscription',
            name='creditcard_type',
            field=models.CharField(blank=True, max_length=10, verbose_name='Tipo de tarjeta inscrita por el cliente'),
        ),
        migrations.AlterField(
            model_name='webpayoneclickinscription',
            name='inscrito',
            field=models.BooleanField(default=False, verbose_name='Esta inscrito correctamente'),
        ),
        migrations.AlterField(
            model_name='webpayoneclickinscription',
            name='response_code',
            field=models.CharField(blank=True, max_length=10, verbose_name='Código respuesta de la autorizacion'),
        ),
        migrations.AlterField(
            model_name='webpayoneclickinscription',
            name='tbk_user',
            field=models.CharField(blank=True, max_length=200, verbose_name='Username del usuario en Transbank'),
        ),
        migrations.AlterField(
            model_name='webpayoneclickinscription',
            name='token',
            field=models.CharField(blank=True, max_length=300, verbose_name='Token proporcionado por Transbank'),
        ),
        migrations.AlterField(
            model_name='webpayoneclickinscription',
            name='user',
            field=models.CharField(max_length=100, primary_key=True, serialize=False, verbose_name='Username del usuario del comercio'),
        ),
        migrations.AlterField(
            model_name='webpayoneclickpayment',
            name='amount',
            field=models.PositiveIntegerField(default=0, verbose_name='Monto transacción'),
        ),
        migrations.AlterField(
            model_name='webpayoneclickpayment',
            name='authorization_code',
            field=models.CharField(blank=True, max_length=8, verbose_name='Código autorización de la transacción'),
        ),
        migrations.AlterField(
            model_name='webpayoneclickpayment',
            name='buy_order',
            field=models.CharField(max_length=42, unique=True, verbose_name='Orden Compra de la tienda'),
        ),
        migrations.AlterField(
            model_name='webpayoneclickpayment',
            name='credit_card_type',
            field=models.CharField(blank=True, max_length=10, verbose_name='Tipo de tarjeta inscrita por el cliente'),
        ),
        migrations.AlterField(
            model_name='webpayoneclickpayment',
            name='inscription',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='oneclick.webpayoneclickinscription'),
        ),
        migrations.AlterField(
            model_name='webpayoneclickpayment',
            name='last4_card_digits',
            field=models.CharField(blank=True, max_length=4, verbose_name='Últimos 4 números de la tarjeta'),
        ),
        migrations.AlterField(
            model_name='webpayoneclickpayment',
            name='response_code',
            field=models.CharField(blank=True, max_length=10, verbose_name='Código respuesta de la autorizacion'),
        ),
        migrations.AlterField(
            model_name='webpayoneclickpayment',
            name='reverse_code',
            field=models.CharField(blank=True, max_length=30, verbose_name='Codigo de transaccion reversada'),
        ),
        migrations.AlterField(
            model_name='webpayoneclickpayment',
            name='transaction_id',
            field=models.CharField(blank=True, max_length=4, verbose_name='Transaction ID'),
        ),
        migrations.AddField(
            model_name='webpayoneclickpayment',
            name='multipleinscription',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='oneclick.webpayoneclickmultipleinscription'),
        ),
    ]
