# Generated by Django 3.1 on 2021-01-26 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oneclick', '0002_auto_20190727_1603'),
    ]

    operations = [
        migrations.AddField(
            model_name='webpayoneclickinscription',
            name='id',
            field=models.IntegerField(default=1, verbose_name='id'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='webpayoneclickinscription',
            name='authorization_code',
            field=models.CharField(blank=True, max_length=8, verbose_name='Código autorización de la transacción'),
        ),
        migrations.AlterField(
            model_name='webpayoneclickinscription',
            name='card_number',
            field=models.CharField(blank=True, max_length=4, verbose_name='Últimos 4 números de la tarjeta'),
        ),
        migrations.AlterField(
            model_name='webpayoneclickinscription',
            name='creditcard_type',
            field=models.CharField(blank=True, max_length=10, verbose_name='Tipo de tarjeta inscrita por el cliente'),
        ),
        migrations.AlterField(
            model_name='webpayoneclickinscription',
            name='date_inscription',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='webpayoneclickinscription',
            name='inscrito',
            field=models.BooleanField(default=False, verbose_name='Esta inscrito correctamente'),
        ),
        migrations.AlterField(
            model_name='webpayoneclickinscription',
            name='response_code',
            field=models.CharField(blank=True, max_length=10, verbose_name='Código respuesta de la autorizacion'),
        ),
        migrations.AlterField(
            model_name='webpayoneclickinscription',
            name='tbk_user',
            field=models.CharField(blank=True, max_length=200, verbose_name='Username del usuario en Transbank'),
        ),
        migrations.AlterField(
            model_name='webpayoneclickinscription',
            name='token',
            field=models.CharField(blank=True, max_length=300, verbose_name='Token proporcionado por Transbank'),
        ),
        migrations.AlterField(
            model_name='webpayoneclickinscription',
            name='user',
            field=models.CharField(max_length=100, primary_key=True, serialize=False, verbose_name='Username del usuario del comercio'),
        ),
        migrations.AlterField(
            model_name='webpayoneclickpayment',
            name='amount',
            field=models.PositiveIntegerField(default=0, verbose_name='Monto transacción'),
        ),
        migrations.AlterField(
            model_name='webpayoneclickpayment',
            name='authorization_code',
            field=models.CharField(blank=True, max_length=8, verbose_name='Código autorización de la transacción'),
        ),
        migrations.AlterField(
            model_name='webpayoneclickpayment',
            name='buy_order',
            field=models.CharField(max_length=42, unique=True, verbose_name='Orden Compra de la tienda'),
        ),
        migrations.AlterField(
            model_name='webpayoneclickpayment',
            name='credit_card_type',
            field=models.CharField(blank=True, max_length=10, verbose_name='Tipo de tarjeta inscrita por el cliente'),
        ),
        migrations.AlterField(
            model_name='webpayoneclickpayment',
            name='last4_card_digits',
            field=models.CharField(blank=True, max_length=4, verbose_name='Últimos 4 números de la tarjeta'),
        ),
        migrations.AlterField(
            model_name='webpayoneclickpayment',
            name='response_code',
            field=models.CharField(blank=True, max_length=10, verbose_name='Código respuesta de la autorizacion'),
        ),
        migrations.AlterField(
            model_name='webpayoneclickpayment',
            name='reverse_code',
            field=models.CharField(blank=True, max_length=30, verbose_name='Codigo de transaccion reversada'),
        ),
        migrations.AlterField(
            model_name='webpayoneclickpayment',
            name='transaction_id',
            field=models.CharField(blank=True, max_length=4, verbose_name='Transaction ID'),
        ),
    ]
