# Generated by Django 3.1 on 2021-01-26 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oneclick', '0003_auto_20210126_1247'),
    ]

    operations = [
        migrations.AlterField(
            model_name='webpayoneclickinscription',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False, verbose_name='id'),
        ),
        migrations.AlterField(
            model_name='webpayoneclickinscription',
            name='user',
            field=models.CharField(max_length=100, verbose_name='Username del usuario del comercio'),
        ),
    ]
