# Generated by Django 3.1 on 2021-01-26 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oneclick', '0004_auto_20210126_1727'),
    ]

    operations = [
        migrations.AlterField(
            model_name='webpayoneclickinscription',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False, verbose_name='id'),
        ),
    ]
